[package]
name = "aimedia-aac"
description = "Runtime-loaded Android libxaac boundary for aimedia"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
aimedia-mpegts = { version = "0.1.0-alpha.1", path = "../aimedia-mpegts" }
libloading.workspace = true
serde.workspace = true
thiserror.workspace = true

[lints]
workspace = true
