apiVersion: aimedia/v1alpha2
kind: MediaJob
metadata:
  name: single-srt-demo

inputs:
  - name: program
    role: custom
    uri: srt://0.0.0.0:9001
    srt:
      mode: listener
      latencyMs: 120

processing:
  timing:
    masterInput: 0
    bufferMs: 1000
    maxSkewMs: 80

outputs:
  - name: program
    uri: srt://127.0.0.1:10000
    srt:
      mode: caller
      latencyMs: 120

taps: []
